### PR TITLE
Backported ImageRenderer for >=iOS13 in the newest compilators

### PR DESCRIPTION
**Pull request by arkus-pm**
1. Added runtime check for iOS version
2. Main init overload mimics ImageRenderer for iOS 16, without size property
3. Now size is optional, with calculation from content's frame. Frame has to be specified though (via .frame() modificator)

This:
``` ImageRenderer(content: Text("Hello").frame(width: 1080, height: 1080))```

Is equivalent to:
``` ImageRenderer(content: Text("Hello"), size: CGSize(width: 1080, height: 1080))```

### CODE REVIEW

**Comment by arkus-pm** [comment]
Might be better idea to make size as optional enum: `.screenSize` and `.contentSize`. Since it's been pretty handy to have just a content in phone's frame size.

**Review by danielsaidi — COMMENTED** [review]
Looks great! But why do we need the @MainActor annotations?

**Comment by arkus-pm** [comment]
> Looks great! But why do we need the @mainactor annotations?

Can't really explain, I've reused this part from the previous version and decided not to change things that work and I am not aware of how

**Comment by danielsaidi** [comment]
Ok :) In that case, I think I will just deprecate the backport altogether since I don't use it myself and having it in the library will just become messy.

Great job with the backport design, though! I hope you can use it in your own projects with great success.

**Pull request closed without merging**
